x = 5
try:
    print(x)
except:
    print("Ocurrio un error")
finally:
    print("Finalizó la ejecución")