# manejo de errores
x = 5
try:
    print(x)
except:
    print("Ocurrio un error")